ALTER TABLE IF EXISTS matches ADD COLUMN IF NOT EXISTS status varchar(255);

UPDATE matches
SET status = 'SCHEDULED'
WHERE status IS NULL;

ALTER TABLE IF EXISTS matches
    ALTER COLUMN status SET DEFAULT 'SCHEDULED';

ALTER TABLE IF EXISTS matches
    ALTER COLUMN status SET NOT NULL;
